### ISSUE TITLE
Unexpected token: operator (<) when using "/>" on "script" tag.

### ISSUE THREAD

**Issue by Kompwu** [posthtml/htmlnano#54] opened 2018-08-02 16:57 UTC
This code cause the issue:
```html
<script src="../ts/options.ts" />
```

**Comment by maltsev** [comment] 2018-08-03 12:10
Unfortunately, I wasn't able to reproduce it :-/

I just released new version [0.1.10](https://www.npmjs.com/package/htmlnano/v/0.1.10). Can you update your app and try again? If you'd get an error again, could you please post the source code, so I'd be able to reproduce the error.

**Comment by Kompwu** [comment] 2018-08-03 20:30
@maltsev [Here](https://github.com/kompwu/audio-only-youtube)
Change: https://github.com/Kompwu/audio-only-youtube/blob/137e8cabe62f2945ce76468122e6f66ec6c9794f/src/html/options.html#L22

To:
```html
<script src="../ts/options.ts" />
```

Then `npm run build:dev`

**Comment by maltsev** [comment] 2018-08-06 18:56
Okay, I was able to reproduce it with another code:
```html
<!DOCTYPE html>
<html>
  <script src="../ts/options.ts" />
</html>
```

Unfortunately, I don't have much spare time this month. Probably I'll look into it in a few weeks.

**Comment by maltsev** [comment] 2018-08-18 12:17
Actually, this code is invalid and breaks a tree structure. Here is the report from [the W3C validator](https://validator.w3.org/) (see the used code below):

- Self-closing syntax (`/>`) used on a non-void HTML element. Ignoring the slash and treating as a start tag.
- End of file seen when expecting text or an end tag.
- Unclosed element `script`.
- The text content of element `script` was not in the required format: Expected space, tab, newline, or slash but found `<` instead.


So unfortunately there is nothing I can do to fix the issue since [posthtml](https://github.com/posthtml/posthtml) itself doesn't handle such invalid HTML.

-----

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Test</title>
    </head>
    <body>
        <script src="../ts/options.js" />
    </body>
</html>
```

**Closed by maltsev** 2018-08-18 12:17 UTC
Labels: bug
