### ISSUE TITLE
`id` attribute of `AnimateTransform` and `AnimateMotion` in inline svg being trimmed

### ISSUE THREAD

**Issue by yw662** [posthtml/htmlnano#77] opened 2019-07-01 19:44 UTC
```pug
    use(href="#foo")
        animateTransform(id="bar"
        attributeName="transform" type="rotate"
        begin="0s" repeatCount="indefinite"
       ......
       )
        animateMotion(id="baz"
        attributeName="transform" type="translate"
        begin="0s" repeatCount="indefinite"
       ......
        )
```

and output:

```html
<use href="#foo" transform="rotate(0)"><animateTransform attributeName="transform" type="rotate" begin="0s" repeatCount="indefinite" ......></animateTransform><animateMotion begin="0s" repeatCount="indefinite" ......></animateMotion></use>
```

**Comment by maltsev** [comment] 2019-07-04 12:23
Unfortunately, I couldn't reproduce it. Can you test it again with [the latest version](https://github.com/posthtml/htmlnano/commit/HEAD) from the master branch? The latest changes shouldn't be related to this bug, though.

If htmlnano would still trim `id`, then could you send me your full code?

**Comment by maltsev** [comment] 2020-08-08 07:25
I'm closing this issue. Feel free to re-open it if you still have this bug.

**Closed by maltsev** 2020-08-08 07:25 UTC
